title: "Yan Yan"
author: "Yan Yan"
description: "Vanderbilt University, Biostatistics"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title = Home}
  - {file: "research.md", title = Research}
  - {url: "https://www.vumc.org/vmac/home", title = Vanderbilt}
  - {file: "research.md", title = Research}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:yyanhust@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/sallymeeyan"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
